funMsgs = {
  "On a scale from one to ten what is your favourite colour of the alphabet.",
  "Llamas eat sexy paper clips",
  "Everyday a grape licks a friendly cow",
  "If your canoe is stuck in a tree with the headlights on, how many pancakes does it take to get to the moon?",
  "Banana error.",
  "Cloth is yum like paper",
  "Thank you for noticing this list, your noticing has been noticed",
  "Screw world peace, I want a pony",
  "There's a purple mushroom in my backyard, screaming Taco's!",
  "Don't touch my crayons, they can smell glue",
  "My nose is a communist.",
  "Metallica ate a hairy garilla with purple nipples then swaped a red tyre with a fire breathing goat last Tuesday at breakfast",
  "Look, a distraction!",
  "Cheese grader shaved my butt skin off",
  "What do you think about the magical yellow unicorn who dances on the rainbow with a spoonful of blue cheese dressing?",
  "I mean, Tree!",
  "I said don't enter the rabbit hole. Now you have the salad.",
  "The sparkly lamp ate a pillow then punched Larry",
  "I like bologna sandwiches",
  "Hi, that duck over there!",
  "Gurklebob is eating eyes with Schadenfreude",
  "Imagination tickles your bed",
  "When life gives you lemons, chuck them at people you hate",
  "WHO TF IS BARB?",
  "Knock knock Who is there A potato eating a hash brown",
  "The cake is not a lie for some reason",
  "My cat ate my homework.",
  "Are confused flowers always so green when they poke toasted bunnies?",
  "Yo Darth Vader",
  "No the radios married the avocados in season 4",
  "A Zebra licked a DVD",
  "Did you ever notice that pineapples never wear bathrobes?",
  "Honey, you stole the bacon! Now ima twerk at gorillas!",
  "I’m bored.",
  "That is why udders bite Orange juice",
  "A baby goat is like a mushroom, I swear if you kill that duck I'm scared of toasters.",
  "We need more cheeeeeeessseeeee!!!",
  "You are my G.O.A.T Greatest Of All Time",
  "if beauty had a name, it would be named after you.",
  "I wish your parents never met!",
  "Yes, I know a message and the message knows me as well",
  "I wanted to send you something that would make you smile, but the mail man told me to get out of the mailbox",
}
